maintainer       "Dell Crowbar Team"
maintainer_email "openstack@dell.com"
license          "Apache 2"
description      "Minicom stuff"
long_description "Default recipe for installing Minicom"
version          "0.9.5"
